---
title: "Rarefaction/estimated richness report"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsplants)
library(SPECIES)

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", "drake-cache.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)

```

## Developing a rarefaction protocol

```{r load stuff}
datnames <- cached(cache = cache)[ which(substr(cached(cache = cache), 1, 3) == "dat")]
datnames <- datnames[ !grepl(datnames, pattern = "singles")]

dat <- readd(datnames[2], character_only = T,  cache = cache)

all_dats <- lapply(datnames, readd, cache = cache, character_only = T)

all_ests <- lapply(all_dats, FUN = function(a_dat) return(try(add_singletons(a_dat))))

all_ests <- all_ests[ which(!is.na(all_ests))]

alldat <- bind_rows(all_dats)
allests <- bind_rows(all_ests)

allests <- allests %>%
  group_by(sim, source, season, year, treatment) %>%
  summarize(n0 = sum(abund),
         s0 = n()) %>%
  ungroup() %>%
  select(season, year, s0, n0) %>%
  rename(est_n0 = n0,
         est_s0 = s0)

alldat <- alldat %>%
  group_by(sim, source, season, year, treatment) %>%
  summarize(n0 = sum(abund),
         s0 = n()) %>%
  ungroup() %>%
  select(season, year, s0, n0)

alldat <- left_join(alldat, allests, by = c("season", "year"))

```

```{r rarefaction, fig.height = 3, fig.width = 6, warning = FALSE, message = FALSE}

ests_plots <- ggplot(data = alldat, aes(x = s0, y = est_s0)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  geom_abline(intercept = 0, slope = 1.1, color = "blue") +
  theme_bw() +
  facet_wrap(vars(season), ncol = 2, strip.position = "top") +
  ylim(0, max(alldat$est_s0, na.rm = T) + 5)

ests_plots

max(alldat$est_s0, na.rm = T)

est_datnames <- cached(cache = cache)[ which(substr(cached(cache = cache), 1, 3) == "dat")]
est_datnames <- est_datnames[ grepl(est_datnames, pattern = "singles")]

all_est_cached <- lapply(est_datnames, readd, cache = cache, character_only = T)

names(all_est_cached) <- est_datnames

all_est_cached <- all_est_cached[ which(!is.na(all_est_cached))]

all_est_cached <- bind_rows(all_est_cached, .id = "est_datname")

head(all_est_cached)

est_statevars <- all_est_cached %>%
  select(season, year, sim, rank, abund, est_datname) %>%
  group_by(season, year, sim, est_datname) %>%
  summarize(cache_n0 = sum(abund), cache_s0 = n()) %>%
  ungroup() %>%
  select(-sim, -est_datname)


alldat <- alldat %>%
  left_join(est_statevars, by = c("season", "year"))

alldat <- alldat %>%
  mutate(s0_match = est_s0 == cache_s0,
         n0_match = est_n0 == cache_n0)

sum(alldat$s0_match, na.rm = T)
sum(alldat$n0_match, na.rm = T)

sum(is.na(alldat$s0_match))

DBI::dbDisconnect(db)
rm(list=ls())

```


```{r load sims}

load(here::here("analysis", "reports", "ranked_dis.Rds"))
fs_df <- read.csv(here::here("analysis", "drake", "fs_df.csv"), stringsAsFactors = F)

fs_df <- fs_df %>%
  filter(source == "observed") %>%
  group_by(fs_name, sim, season, year) %>%
  mutate(S = n(), 
         N = sum(abund)) %>%
  ungroup()

ranked_di_df <- ranked_di_df %>%
  filter(source == "observed") %>%
  select(-sim) %>%
  mutate(fs_name = substr(di_name, 4, nchar(di_name))) %>%
  left_join(fs_df, by = c("fs_name", "source", "season", "year", "treatment"))

ranked_di_long_fs <- ranked_di_df %>%
  select(-skew, -shannon, -simpson, -fs_name, -di_name, -sim, -treatment) %>%
  tidyr::gather(-source, -season, -singletons, -S, -N, -abund, -year, -rank, key = "variable", value = "value")
```


```{r plot statevars}

sv <- ranked_di_df %>%
  select(singletons, season, year, S, N) %>%
  distinct()

sv_singles <- filter(sv, singletons == "singletons") %>%
  select(-singletons) %>%
  rename(S_est = S, N_est = N)

sv_wide <- filter(sv, singletons == "true") %>%
  select(-singletons) %>%
  left_join(sv_singles, by = c("season", "year")) %>%
  mutate(s_change = S_est - S)

```

```{r plot singleton v raw, fig.height= 100, fig.width = 7}

rare_plots <- ggplot(data = ranked_di_long_fs, aes(x = rank, y = abund, group = singletons, color = value)) +
  geom_line() + 
  theme_bw() +
  facet_wrap(vars(year, season, variable), strip.position = "top", scales = "free", ncol = 3) +
  scale_color_viridis_c(end = .8, option = "plasma")

# rare_plots
```


### Sensitivity of percentile to adding singletons
```{r singletons 1to1, fig.width = 4.5, fig.height = 6}

singletons_1to1_dat <- filter(ranked_di_long, source == "observed", variable %in% c("skew_percentile", "shannon_percentile", "simpson_percentile"), singletons == "true") %>%
  select(-di_name) %>%
  left_join(filter(ranked_di_long, source == "observed", variable %in% c("skew_percentile", "shannon_percentile", "simpson_percentile"), singletons == "singletons"), by = c("sim", "year", "season", "treatment", "source", "variable")) %>%
  select(-sim, -di_name) %>%
  rename(true_value = value.x,
         singletons_value = value.y) %>%
  select(-singletons.x, -singletons.y) %>%
  filter(!is.na(singletons_value))

singletons_1to1_plot <- ggplot(data = singletons_1to1_dat, aes(x = true_value, y = singletons_value, color = season)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, alpha = .5) +
  theme_bw() +
  facet_wrap(vars(variable, season), ncol = 2) +  
  scale_color_viridis_d(end = .8, direction = -1)


singletons_1to1_plot
```


Is the amount of percentile change linked to the number of elements we got from the FS?


```{r percentile change v fs size}
di_df <- read.csv(here::here("analysis", "drake", "di_df.csv"), stringsAsFactors = F)

fs_size_info <- di_df %>%
  filter(sim != -99, singletons == "true") %>%
  select(season, year, treatment) %>%
  group_by(season, year, treatment) %>%
  summarize(n_elements = n()) %>%
  ungroup() %>%
  left_join(sv_wide, by = c("season", "year"))

percentile_change <- singletons_1to1_dat %>%
  mutate(singletons_change = singletons_value - true_value) %>%
  mutate(abs_change = abs(singletons_change)) %>%
  left_join(fs_size_info, by = c("season", "year", "treatment")) %>%
  filter(!is.na(singletons_value))

pc_plot <- ggplot(data = percentile_change, aes(x = season, y = singletons_change, color = season)) +
  geom_boxplot() +
  theme_bw() + 
  scale_color_viridis_d(end = .8, direction = -1) +
  facet_wrap(vars(variable), strip.pos = "top") +
  ggtitle("Change in percentile of true vs. with singletons")
pc_plot

nel_pc <- ggplot(data = percentile_change, aes(x = n_elements, y = singletons_change, color = season)) +
  geom_jitter() +
  theme_bw() +
  scale_color_viridis_d(end = .8, direction = -1) +
  facet_wrap(vars(season, variable), scales = "fixed", strip.pos = "top") +
  ggtitle("Change in percentile vs. number of unique draws from FS")
nel_pc

statevars_pc <- ggplot(data = percentile_change, aes(x = s_change, y = singletons_change, color = season)) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_d(end = .8, direction = -1) +
  facet_wrap(vars(season, variable), strip.pos = "top") +
  ggtitle("Percentile change vs. change in number of species")

statevars_pc

```

Does adding singletons change our conclusions about weirdness?

```{r conclusions sensitivity}

conclusions_dat <- ranked_di_df %>%
  select(season, year, source, singletons, simpson_percentile, skew_percentile) %>%
  distinct() %>%
  filter(source == "observed",
         !is.na(simpson_percentile), 
         !is.na(skew_percentile)) %>%
  select(-source) %>%
  mutate(skew_outlier_95 = skew_percentile >= 95,
         skew_outlier_97p5 = skew_percentile >= 97.5,
         simpson_outlier_5 = simpson_percentile <= 5,
         simpson_outlier_2p5 = simpson_percentile <= 2.5) %>%
  tidyr::gather(-season, -year, -singletons, key = "variable", value = "value")

singletons_conclusions <- filter(conclusions_dat, singletons == "singletons") %>%
  select(-singletons) %>%
  rename(singletons_value = value)

conclusions_dat2 <- filter(conclusions_dat, singletons == "true") %>%
  select(-singletons) %>%
  left_join(singletons_conclusions, by = c("year", "season", "variable")) %>%
  filter(!is.na(singletons_value),
         grepl(variable, pattern = "outlier")) %>%
  mutate(singletons_change = singletons_value != value) %>%
  left_join(sv_wide, by = c("year", "season"))

conclusions_plot <- ggplot(data = conclusions_dat2, aes(x = s_change, y = singletons_change)) +
  geom_point() +
  facet_wrap(vars(variable)) +
  theme_bw()

conclusions_plot

```
